/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lk.ijse.payroll.view;

import java.io.InputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.payroll.controller.AllowanceController;
import lk.ijse.payroll.controller.DeductionController;
import lk.ijse.payroll.controller.EmployeeAttendanceController;
import lk.ijse.payroll.controller.EmployeeRegisterController;
import lk.ijse.payroll.dbconnection.DBConnection;
import lk.ijse.payroll.entity.Allowance;
import lk.ijse.payroll.model.AllowanceDTO;
import lk.ijse.payroll.model.AttendanceDTO;
import lk.ijse.payroll.model.DeductionDTO;
import lk.ijse.payroll.model.EmployeeDTO;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.util.HashNMap;

/**
 *
 * @author Shashika
 */
public class EmployeeSalary extends javax.swing.JPanel {
    private String employeeName;

    /** Creates new form EmployeeSalary */
    public EmployeeSalary() {
        initComponents();
        loadEmployeeName();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmpAtt = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelEmployeeName = new javax.swing.JLabel();
        jLabelDesignation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelEmployeeID = new javax.swing.JLabel();
        jComboBoxEmpName = new javax.swing.JComboBox<>();
        jLabelBasicSalary = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelIncentivesAmount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jTextFieldTotalIncentives = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTextFieldHouseRentAllo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jTextFieldCapitalCost = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jTextFieldMedical = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelIncentivesAmount1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jTextFieldTotalDedution = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jTextFieldInsuarance = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jTextFieldWelfare = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jTextFieldETF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jTextFieldNetSalary = new javax.swing.JTextField();
        jLabelAdd = new javax.swing.JLabel();
        jLabelCancel = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        TxtSalary = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jSeparator21 = new javax.swing.JSeparator();
        TxtDesignation = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        TxtId = new javax.swing.JTextField();
        jLabelBasicSalary1 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        TxtSalaryId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        TxtOverTime = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        TxtGrossSalary = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        TxtLateHoursRate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1156, 760));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmpAtt.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        jLabelEmpAtt.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmpAtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payroll/asset/icons8_Purchase_Order_30px_1.png"))); // NOI18N
        jLabelEmpAtt.setText(" Pay Slip");
        add(jLabelEmpAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 40));

        jSeparator4.setBackground(new java.awt.Color(210, 215, 211));
        jSeparator4.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setOpaque(true);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 20, -1, 40));

        jSeparator2.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1630, 10));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator1.setDoubleBuffered(true);
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1630, -1));

        jLabelEmployeeName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelEmployeeName.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeName.setText("Employee Name");
        add(jLabelEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 30));

        jLabelDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelDesignation.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation.setText("Designation");
        add(jLabelDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 58, 147));
        jLabel1.setText("Date");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 50, 30));

        jLabelEmployeeID.setBackground(new java.awt.Color(1, 50, 67));
        jLabelEmployeeID.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelEmployeeID.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeID.setText("Employee ID");
        add(jLabelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 110, 30));

        jComboBoxEmpName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jComboBoxEmpName.setForeground(new java.awt.Color(31, 58, 147));
        jComboBoxEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpNameActionPerformed(evt);
            }
        });
        add(jComboBoxEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, 30));

        jLabelBasicSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelBasicSalary.setForeground(new java.awt.Color(31, 58, 147));
        jLabelBasicSalary.setText("Basic Salary");
        add(jLabelBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 110, 30));

        jSeparator3.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1760, 10));

        jLabelIncentivesAmount.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelIncentivesAmount.setForeground(new java.awt.Color(31, 58, 147));
        jLabelIncentivesAmount.setText("Allowance Amount");
        add(jLabelIncentivesAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 220, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 58, 147));
        jLabel2.setText("Gross Salary");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 140, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 58, 147));
        jLabel3.setText("House Rent Allowance");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 58, 147));
        jLabel4.setText("Vehicle Allowance");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 58, 147));
        jLabel7.setText("Medical");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 30));

        jSeparator11.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator11.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator11.setOpaque(true);
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 170, -1));

        jTextFieldTotalIncentives.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldTotalIncentives.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldTotalIncentives.setBorder(null);
        jTextFieldTotalIncentives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalIncentivesActionPerformed(evt);
            }
        });
        add(jTextFieldTotalIncentives, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 170, 30));

        jSeparator6.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator6.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator6.setOpaque(true);
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 170, -1));

        jTextFieldHouseRentAllo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldHouseRentAllo.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldHouseRentAllo.setBorder(null);
        jTextFieldHouseRentAllo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHouseRentAlloActionPerformed(evt);
            }
        });
        add(jTextFieldHouseRentAllo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 170, 30));

        jSeparator7.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator7.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator7.setOpaque(true);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 170, -1));

        jTextFieldCapitalCost.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldCapitalCost.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldCapitalCost.setBorder(null);
        jTextFieldCapitalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCapitalCostActionPerformed(evt);
            }
        });
        add(jTextFieldCapitalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 170, 30));

        jSeparator10.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator10.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator10.setOpaque(true);
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 170, -1));

        jTextFieldMedical.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldMedical.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldMedical.setBorder(null);
        jTextFieldMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMedicalActionPerformed(evt);
            }
        });
        add(jTextFieldMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 170, 30));

        jSeparator5.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 10, 430));

        jLabelIncentivesAmount1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelIncentivesAmount1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelIncentivesAmount1.setText("Deduction Amount");
        add(jLabelIncentivesAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 220, 40));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 58, 147));
        jLabel8.setText("E.P.F");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 200, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 58, 147));
        jLabel9.setText("Insuarance");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 200, 30));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 58, 147));
        jLabel10.setText("Welfare");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 200, 30));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(31, 58, 147));
        jLabel13.setText("Total Deduction");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 200, 30));

        jSeparator16.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator16.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator16.setOpaque(true);
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 140, -1));

        jTextFieldTotalDedution.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldTotalDedution.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldTotalDedution.setBorder(null);
        jTextFieldTotalDedution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalDedutionActionPerformed(evt);
            }
        });
        add(jTextFieldTotalDedution, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 140, 30));

        jSeparator15.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator15.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator15.setOpaque(true);
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 140, -1));

        jTextFieldInsuarance.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldInsuarance.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldInsuarance.setBorder(null);
        jTextFieldInsuarance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsuaranceActionPerformed(evt);
            }
        });
        add(jTextFieldInsuarance, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 140, 30));

        jSeparator13.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator13.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator13.setOpaque(true);
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, 140, -1));

        jTextFieldWelfare.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldWelfare.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldWelfare.setBorder(null);
        jTextFieldWelfare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWelfareActionPerformed(evt);
            }
        });
        add(jTextFieldWelfare, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 140, 30));

        jSeparator12.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator12.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator12.setOpaque(true);
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, 140, -1));

        jTextFieldETF.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldETF.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldETF.setBorder(null);
        jTextFieldETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldETFActionPerformed(evt);
            }
        });
        add(jTextFieldETF, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, 140, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(31, 58, 147));
        jLabel14.setText("Net Salary");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 200, 30));

        jSeparator17.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator17.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator17.setOpaque(true);
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, 200, -1));

        jTextFieldNetSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldNetSalary.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldNetSalary.setBorder(null);
        jTextFieldNetSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNetSalaryActionPerformed(evt);
            }
        });
        add(jTextFieldNetSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 200, 30));

        jLabelAdd.setBackground(new java.awt.Color(34, 49, 63));
        jLabelAdd.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelAdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdd.setText("Save");
        jLabelAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelAdd.setOpaque(true);
        add(jLabelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 900, 150, 40));

        jLabelCancel.setBackground(new java.awt.Color(34, 49, 63));
        jLabelCancel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancel.setText("Cancel");
        jLabelCancel.setOpaque(true);
        add(jLabelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 900, 150, 40));

        jSeparator20.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator20.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator20.setOpaque(true);
        add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 150, -1));

        TxtSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtSalary.setForeground(new java.awt.Color(31, 58, 147));
        TxtSalary.setBorder(null);
        TxtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalaryActionPerformed(evt);
            }
        });
        add(TxtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 150, 30));

        jXDatePicker1.setForeground(new java.awt.Color(31, 58, 147));
        jXDatePicker1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });
        add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 150, 30));

        jSeparator21.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator21.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator21.setOpaque(true);
        add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, -1));

        TxtDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtDesignation.setForeground(new java.awt.Color(31, 58, 147));
        TxtDesignation.setBorder(null);
        TxtDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDesignationActionPerformed(evt);
            }
        });
        add(TxtDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, 30));

        jSeparator22.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator22.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator22.setOpaque(true);
        add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 60, -1));

        TxtId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtId.setForeground(new java.awt.Color(31, 58, 147));
        TxtId.setBorder(null);
        TxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdActionPerformed(evt);
            }
        });
        add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 60, 30));

        jLabelBasicSalary1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelBasicSalary1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelBasicSalary1.setText("Salary Id");
        add(jLabelBasicSalary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 110, 30));

        jSeparator23.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator23.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator23.setOpaque(true);
        add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 60, -1));

        TxtSalaryId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtSalaryId.setForeground(new java.awt.Color(31, 58, 147));
        TxtSalaryId.setBorder(null);
        TxtSalaryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalaryIdActionPerformed(evt);
            }
        });
        add(TxtSalaryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, 60, 30));

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 110, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 58, 147));
        jLabel5.setText("Total Incentives");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 200, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 58, 147));
        jLabel11.setText("Over Time Payment");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 200, 30));

        jSeparator14.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator14.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator14.setOpaque(true);
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 170, -1));

        TxtOverTime.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtOverTime.setForeground(new java.awt.Color(31, 58, 147));
        TxtOverTime.setBorder(null);
        TxtOverTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOverTimeActionPerformed(evt);
            }
        });
        add(TxtOverTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 170, 30));

        jSeparator18.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator18.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator18.setOpaque(true);
        add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 620, 200, -1));

        TxtGrossSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtGrossSalary.setForeground(new java.awt.Color(31, 58, 147));
        TxtGrossSalary.setBorder(null);
        TxtGrossSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGrossSalaryActionPerformed(evt);
            }
        });
        add(TxtGrossSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 200, 30));

        jSeparator19.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator19.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator19.setOpaque(true);
        add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 140, -1));

        TxtLateHoursRate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtLateHoursRate.setForeground(new java.awt.Color(31, 58, 147));
        TxtLateHoursRate.setBorder(null);
        TxtLateHoursRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLateHoursRateActionPerformed(evt);
            }
        });
        add(TxtLateHoursRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 140, 30));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(31, 58, 147));
        jLabel15.setText("Late Hours Rate");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalIncentivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalIncentivesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalIncentivesActionPerformed

    private void jTextFieldHouseRentAlloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHouseRentAlloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHouseRentAlloActionPerformed

    private void jTextFieldCapitalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCapitalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCapitalCostActionPerformed

    private void jTextFieldMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMedicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMedicalActionPerformed

    private void jTextFieldTotalDedutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalDedutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalDedutionActionPerformed

    private void jTextFieldInsuaranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsuaranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsuaranceActionPerformed

    private void jTextFieldWelfareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWelfareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWelfareActionPerformed

    private void jTextFieldETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldETFActionPerformed

    private void jTextFieldNetSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNetSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNetSalaryActionPerformed

    private void TxtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalaryActionPerformed

    private void TxtDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDesignationActionPerformed

    private void TxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdActionPerformed

    private void TxtSalaryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalaryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalaryIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       InputStream input=getClass().getResourceAsStream("/lk/ijse/payroll/report/Employee1.jasper");
       HashMap map=new HashMap();
       
        try {
            JasperPrint jasperPrint=JasperFillManager.fillReport(input, map,DBConnection.getInstance().getConnection());
            JasperViewer.viewReport(jasperPrint);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpNameActionPerformed
    employeeName = jComboBoxEmpName.getSelectedItem().toString();
        try {
            String empoyeeName=(String) jComboBoxEmpName.getSelectedItem();
            EmployeeDTO employee=EmployeeRegisterController.searchEmployee(empoyeeName);
            ArrayList<AllowanceDTO> allowanceList ;
            if(employee!=null){
                TxtId.setText(employee.getId());
                TxtDesignation.setText(employee.getDesignation());
                TxtSalary.setText(""+employee.getSalary());
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_jComboBoxEmpNameActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        employeeName = jComboBoxEmpName.getSelectedItem().toString();
        double hraAmt =0.0,vaAmt =0.0,medicalAmt =0.0, totalAllowance = 0.0, epfAmt=0.0, welFareAmt=0.0, insuaranceAmt=0.0, totalDeduction=0.0, othours=0.0, otrate=0.0, LateHrshours=0.0,LateHrsrate=0.0, grossSalary=0.0;
        String selectDate = ""+new java.sql.Date( jXDatePicker1.getDate().getTime());
        
        try {
            String empoyeeName=(String) jComboBoxEmpName.getSelectedItem();
            EmployeeDTO employee=EmployeeRegisterController.searchEmployee(empoyeeName);
            if(employee!=null){
               //System.out.print("Date>>>>>>>"+selectDate); 
            ArrayList<AttendanceDTO> attendanceList = EmployeeAttendanceController.getAttendanceById(employee.getId());
            
            for(AttendanceDTO attendance : attendanceList){
                othours += attendance.getOThrs();
            }
                otrate = employee.getOverTimeHoursRate();
                
            for(AttendanceDTO attendance : attendanceList){
                LateHrshours += attendance.getLateHrs();
            }
                
                LateHrsrate = employee.getLateHoursRate();
                
               ArrayList<AllowanceDTO> allowanceList = AllowanceController.getAllowanceByIdAndDate(employee.getId(),selectDate);
               //System.out.print("Show>>>>>>>"+allowanceList.toString());
                for(AllowanceDTO allowance : allowanceList){
                    hraAmt += allowance.getHouserentAllowance();
                    vaAmt += allowance.getVehicleAllowance();
                    medicalAmt += allowance.getMedical();
                    
                }
                totalAllowance = hraAmt+vaAmt+medicalAmt+otrate;
                
               
                ArrayList<DeductionDTO> deductionlist = DeductionController.getDeductionByIdAndDate(employee.getId(),selectDate);
                
                for(DeductionDTO deduction : deductionlist){
                    epfAmt += deduction.getEpf();
                    welFareAmt += deduction.getWelFare();
                    insuaranceAmt += deduction.getInsurance();
                }
                totalDeduction = epfAmt+welFareAmt+insuaranceAmt+LateHrsrate;
                
//                double salary=Double.parseDouble(TxtSalary.getText());
//                double totalAlow=Double.parseDouble(jTextFieldTotalIncentives.getText());
//                TxtGrossSalary.setText(salary+totalAlow+"");
                totalDeduction = epfAmt+welFareAmt+insuaranceAmt+LateHrsrate;
               
                double salary=Double.parseDouble(TxtSalary.getText());
                System.out.print("Show salary>>>>>>>"+salary);
                double totalAlow=Double.parseDouble(jTextFieldTotalIncentives.getText());
                System.out.print("Show allowance>>>>>>>"+totalAlow);
                double gross = salary + totalAlow;
                System.out.print("Show gross>>>>>>>"+gross);
                TxtGrossSalary.setText(gross+"");
//                
                jTextFieldHouseRentAllo.setText(""+hraAmt);
                jTextFieldCapitalCost.setText(""+vaAmt);
                jTextFieldMedical.setText(""+medicalAmt);
                TxtOverTime.setText(""+otrate);
                jTextFieldTotalIncentives.setText(""+totalAllowance);
                
                jTextFieldETF.setText(""+epfAmt);
                jTextFieldWelfare.setText(""+welFareAmt);
                jTextFieldInsuarance.setText(""+insuaranceAmt);
                TxtLateHoursRate.setText(""+LateHrsrate);
                jTextFieldTotalDedution.setText(""+totalDeduction);
              
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void TxtOverTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOverTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOverTimeActionPerformed

    private void TxtGrossSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGrossSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGrossSalaryActionPerformed

    private void TxtLateHoursRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLateHoursRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLateHoursRateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDesignation;
    private javax.swing.JTextField TxtGrossSalary;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtLateHoursRate;
    private javax.swing.JTextField TxtOverTime;
    private javax.swing.JTextField TxtSalary;
    private javax.swing.JTextField TxtSalaryId;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxEmpName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelBasicSalary1;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelDesignation;
    private javax.swing.JLabel jLabelEmpAtt;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JLabel jLabelIncentivesAmount;
    private javax.swing.JLabel jLabelIncentivesAmount1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextFieldCapitalCost;
    private javax.swing.JTextField jTextFieldETF;
    private javax.swing.JTextField jTextFieldHouseRentAllo;
    private javax.swing.JTextField jTextFieldInsuarance;
    private javax.swing.JTextField jTextFieldMedical;
    private javax.swing.JTextField jTextFieldNetSalary;
    private javax.swing.JTextField jTextFieldTotalDedution;
    private javax.swing.JTextField jTextFieldTotalIncentives;
    private javax.swing.JTextField jTextFieldWelfare;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables

    private void loadEmployeeName() {
        try {
            ArrayList<String>employeeNames=EmployeeRegisterController.getAllEmployeeNames();
            for (String employeeName : employeeNames) {
                jComboBoxEmpName.addItem(employeeName);
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    private double getOvertimertTot(double rate, int hours) {
        System.out.println(""+rate+","+hours);
        double deductionAmt = rate * hours;
        return deductionAmt;
    }
    
    private double getLatehoursTot(double rate, int hours) {
       double deductionAmt = rate * hours;
        return deductionAmt;
    }

    

}
