/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payroll.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.payroll.business.custom.EmployeeBO;
import lk.ijse.payroll.business.custom.impl.EmployeeBOImpl;
import lk.ijse.payroll.common.IdGenerater;
import lk.ijse.payroll.controller.EmployeeAttendanceController;
import lk.ijse.payroll.controller.EmployeeRegisterController;
import lk.ijse.payroll.model.AttendanceDTO;
import lk.ijse.payroll.model.EmployeeDTO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Shashika
 */
public class EmployeeAttendance extends javax.swing.JPanel {
    ButtonGroup bg;
    private String dayStatus="",dayType="",date = "",employeeName;
    private String employeeId="";           
    DefaultTableModel dtm;          
    private EmployeeBO employeeBO;
    /**
     * Creates new form Attendance
     */
    public EmployeeAttendance() {
        initComponents();
        //setInTime();
        commenMethod();
       
    }
    public void commenMethod(){
        loadEmployeeName();
        groupButtonAttendance();
        attendanceId();
        tableView();
        //setTiime();
        AutoCompleteDecorator.decorate(jComboBoxEmpName);
        employeeBO = new EmployeeBOImpl();
        dtm=(DefaultTableModel) TableAttendance.getModel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmpAtt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        BtnAdd = new javax.swing.JButton();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jLabelEmployeeID = new javax.swing.JLabel();
        jLabelEmployeeName = new javax.swing.JLabel();
        jLabelDesignation = new javax.swing.JLabel();
        DatePickerDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jTextFieldDesignation = new javax.swing.JTextField();
        CheckBoxHalf = new javax.swing.JCheckBox();
        RadioButtonPrasent = new javax.swing.JRadioButton();
        RadioButtonLeave = new javax.swing.JRadioButton();
        OutTimeLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDesignation1 = new javax.swing.JLabel();
        jLabelDesignation2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        OthTxt = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        LtTxt = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelEmployeeName1 = new javax.swing.JLabel();
        jTextFieldAttendanceId = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        InTimeLbl = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        TxtEmployeeId = new javax.swing.JTextField();
        jComboBoxEmpName = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAttendance = new org.jdesktop.swingx.JXTable();
        BtnAdd1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1156, 760));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmpAtt.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelEmpAtt.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmpAtt.setText(" Employee Attendance");
        add(jLabelEmpAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 40));

        jSeparator2.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 1640, -1));

        jSeparator4.setBackground(new java.awt.Color(210, 215, 211));
        jSeparator4.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setOpaque(true);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        BtnAdd.setBackground(new java.awt.Color(31, 58, 147));
        BtnAdd.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        BtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });
        add(BtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 130, 30));

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmployeeID.setBackground(new java.awt.Color(1, 50, 67));
        jLabelEmployeeID.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelEmployeeID.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeID.setText("Employee ID");
        jXPanel1.add(jLabelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        jLabelEmployeeName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelEmployeeName.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeName.setText("Employee Name");
        jXPanel1.add(jLabelEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 30));

        jLabelDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelDesignation.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation.setText("Designation");
        jXPanel1.add(jLabelDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        DatePickerDate.setForeground(new java.awt.Color(31, 58, 147));
        DatePickerDate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        DatePickerDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatePickerDateActionPerformed(evt);
            }
        });
        jXPanel1.add(DatePickerDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 190, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 58, 147));
        jLabel2.setText("Date");
        jXPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 30));

        jSeparator16.setBackground(new java.awt.Color(0, 139, 139));
        jSeparator16.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator16.setOpaque(true);
        jXPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 190, -1));

        jTextFieldDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldDesignation.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldDesignation.setBorder(null);
        jXPanel1.add(jTextFieldDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 190, 30));

        CheckBoxHalf.setBackground(new java.awt.Color(255, 255, 255));
        CheckBoxHalf.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        CheckBoxHalf.setForeground(new java.awt.Color(31, 58, 147));
        CheckBoxHalf.setText(" Half-Day");
        CheckBoxHalf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxHalfActionPerformed(evt);
            }
        });
        jXPanel1.add(CheckBoxHalf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 110, -1));

        RadioButtonPrasent.setBackground(new java.awt.Color(255, 255, 255));
        RadioButtonPrasent.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        RadioButtonPrasent.setForeground(new java.awt.Color(31, 58, 147));
        RadioButtonPrasent.setText(" Prasent");
        RadioButtonPrasent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonPrasentActionPerformed(evt);
            }
        });
        jXPanel1.add(RadioButtonPrasent, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 110, 30));

        RadioButtonLeave.setBackground(new java.awt.Color(255, 255, 255));
        RadioButtonLeave.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        RadioButtonLeave.setForeground(new java.awt.Color(31, 58, 147));
        RadioButtonLeave.setText(" Leave");
        RadioButtonLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonLeaveActionPerformed(evt);
            }
        });
        jXPanel1.add(RadioButtonLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 110, 30));

        OutTimeLbl.setBackground(new java.awt.Color(255, 255, 255));
        OutTimeLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        OutTimeLbl.setForeground(new java.awt.Color(31, 58, 147));
        OutTimeLbl.setOpaque(true);
        jXPanel1.add(OutTimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 100, 30));
        jXPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 490, 10));

        jLabelDesignation1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelDesignation1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation1.setText("Late hours");
        jXPanel1.add(jLabelDesignation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 120, 30));

        jLabelDesignation2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelDesignation2.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation2.setText("Over Time hours");
        jXPanel1.add(jLabelDesignation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, 30));
        jXPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 490, 10));

        OthTxt.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        OthTxt.setForeground(new java.awt.Color(31, 58, 147));
        OthTxt.setBorder(null);
        jXPanel1.add(OthTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 70, 30));

        jSeparator17.setBackground(new java.awt.Color(0, 139, 139));
        jSeparator17.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator17.setOpaque(true);
        jXPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 70, -1));

        LtTxt.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LtTxt.setForeground(new java.awt.Color(31, 58, 147));
        LtTxt.setBorder(null);
        jXPanel1.add(LtTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 70, 30));

        jSeparator18.setBackground(new java.awt.Color(0, 139, 139));
        jSeparator18.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator18.setOpaque(true);
        jXPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 70, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jXPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 10, 260));
        jXPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 490, 10));

        jLabelEmployeeName1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelEmployeeName1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeName1.setText("Attendance ID");
        jXPanel1.add(jLabelEmployeeName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 150, 30));

        jTextFieldAttendanceId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jTextFieldAttendanceId.setForeground(new java.awt.Color(31, 58, 147));
        jTextFieldAttendanceId.setBorder(null);
        jTextFieldAttendanceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAttendanceIdActionPerformed(evt);
            }
        });
        jXPanel1.add(jTextFieldAttendanceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 50, 30));

        jSeparator19.setBackground(new java.awt.Color(0, 139, 139));
        jSeparator19.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator19.setOpaque(true);
        jXPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 50, -1));

        InTimeLbl.setBackground(new java.awt.Color(255, 255, 255));
        InTimeLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        InTimeLbl.setForeground(new java.awt.Color(31, 58, 147));
        InTimeLbl.setOpaque(true);
        jXPanel1.add(InTimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 100, 30));

        jSeparator22.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator22.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator22.setOpaque(true);
        jXPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 70, -1));

        TxtEmployeeId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtEmployeeId.setForeground(new java.awt.Color(31, 58, 147));
        TxtEmployeeId.setBorder(null);
        TxtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmployeeIdActionPerformed(evt);
            }
        });
        jXPanel1.add(TxtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 70, 20));

        jComboBoxEmpName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jComboBoxEmpName.setForeground(new java.awt.Color(31, 58, 147));
        jComboBoxEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpNameActionPerformed(evt);
            }
        });
        jXPanel1.add(jComboBoxEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, 30));

        add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1060, 280));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Attendance List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Light", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "EID", "Name", "Designation", "Date", "Attendance", "In-Time", "Out-Time"
            }
        ));
        jScrollPane2.setViewportView(TableAttendance);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1040, 160));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 1060, 200));

        BtnAdd1.setBackground(new java.awt.Color(31, 58, 147));
        BtnAdd1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        BtnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd1.setText("Cancel");
        BtnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdd1ActionPerformed(evt);
            }
        });
        add(BtnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
       AttendanceDTO attendance =new AttendanceDTO(
               jTextFieldAttendanceId.getText(), 
               TxtEmployeeId.getText(),
               dayStatus,
               dayType,
               date,
               Integer.parseInt(OthTxt.getText()),
               Integer.parseInt(LtTxt.getText()),
               InTimeLbl.getText(),
               OutTimeLbl.getText());
            try {
                
                boolean result = EmployeeAttendanceController.addAttendance(attendance);
                if(validation()){
                    if (result){
                        JOptionPane.showMessageDialog(this, "Saved successfully");
                        clearTextFields();
                        tableView();
                    }else{
                        JOptionPane.showMessageDialog(this, "Failed to Save");
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(EmployeeAttendance.class.getName()).log(Level.SEVERE, null, ex);
            }
     
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdd1ActionPerformed

    private void RadioButtonPrasentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonPrasentActionPerformed
        dayStatus="Present";
    }//GEN-LAST:event_RadioButtonPrasentActionPerformed

    private void RadioButtonLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonLeaveActionPerformed
        dayStatus="Leave";
    }//GEN-LAST:event_RadioButtonLeaveActionPerformed

    private void CheckBoxHalfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxHalfActionPerformed
        dayType="Half Day";
    }//GEN-LAST:event_CheckBoxHalfActionPerformed

    private void DatePickerDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatePickerDateActionPerformed
        //System.out.println("Date>>"+new java.sql.Date(DatePickerDate.getDate().getTime()));
        date =    ""+ new java.sql.Date(DatePickerDate.getDate().getTime());

    }//GEN-LAST:event_DatePickerDateActionPerformed

    private void jTextFieldAttendanceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAttendanceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAttendanceIdActionPerformed

    private void TxtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmployeeIdActionPerformed

    private void jComboBoxEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpNameActionPerformed
        employeeName = jComboBoxEmpName.getSelectedItem().toString();
        try {
            String empoyeeName=(String) jComboBoxEmpName.getSelectedItem();
            EmployeeDTO employee=EmployeeRegisterController.searchEmployee(empoyeeName);
            if(employee!=null){
                TxtEmployeeId.setText(employee.getId());
                jTextFieldDesignation.setText(employee.getDesignation());
               
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAllowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxEmpNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnAdd1;
    private javax.swing.JCheckBox CheckBoxHalf;
    private org.jdesktop.swingx.JXDatePicker DatePickerDate;
    private javax.swing.JLabel InTimeLbl;
    private javax.swing.JTextField LtTxt;
    private javax.swing.JTextField OthTxt;
    private javax.swing.JLabel OutTimeLbl;
    private javax.swing.JRadioButton RadioButtonLeave;
    private javax.swing.JRadioButton RadioButtonPrasent;
    private org.jdesktop.swingx.JXTable TableAttendance;
    private javax.swing.JTextField TxtEmployeeId;
    private javax.swing.JComboBox<String> jComboBoxEmpName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDesignation;
    private javax.swing.JLabel jLabelDesignation1;
    private javax.swing.JLabel jLabelDesignation2;
    private javax.swing.JLabel jLabelEmpAtt;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JLabel jLabelEmployeeName1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldAttendanceId;
    private javax.swing.JTextField jTextFieldDesignation;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    // End of variables declaration//GEN-END:variables

   

    private void loadEmployeeName() {
         try {
            ArrayList<String>employeeNames=EmployeeRegisterController.getAllEmployeeNames();
            for (String employeeName : employeeNames) {
                jComboBoxEmpName.addItem(employeeName);
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   

    

    private void groupButtonAttendance() {
        ButtonGroup bg=new ButtonGroup();
        
        bg.add(RadioButtonPrasent);
        bg.add(RadioButtonLeave);
    }

    private void attendanceId() {
        try {
            String attendanceId;
            attendanceId = IdGenerater.getNewID("attendance", "Id", "A");
            jTextFieldAttendanceId.setText(attendanceId);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeAttendance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    private void setInTime() {  
         
    }

    private void tableView() {
        try {

            ArrayList<AttendanceDTO> allAttendances= EmployeeAttendanceController.getAttendance();
            dtm = (DefaultTableModel) TableAttendance.getModel();
            dtm.setRowCount(0);
            if(allAttendances==null){return;}
            
                dtm.setRowCount(0);
            for (AttendanceDTO attendance : allAttendances) {

                    Object[] rowData = {
                        attendance.getEmployeeId(),
                        EmployeeRegisterController.searchEmployeeID(attendance.getEmployeeId()).getName(),
                        EmployeeRegisterController.searchEmployeeID(attendance.getEmployeeId()).getDesignation(),
                        attendance.getDate(),
                        attendance.getDayStatus(),
                        attendance.getInTime(),
                        attendance.getOutTime()
                    };
                    dtm.addRow(rowData);

            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void clearTextFields(){
        TxtEmployeeId.setText("");
        jTextFieldDesignation.setText("");
        DatePickerDate.setDate(null);
        jTextFieldAttendanceId.setText("");
        bg.clearSelection();
       // CheckBoxHalf.
    }
    
    public boolean validation(){
        if( OthTxt.getText().equals("") || LtTxt.getText().equals("")){
            return false;
        }else if(OthTxt.getText()== null || LtTxt.getText()== null ){
            return false;
        }
        return true;
    }

     private void nowTime() {
//        new Thread(() -> {
//            while (true) {
//                Date date = new Date();
//                String currentdate = new SimpleDateFormat("hh:mm:ss aa").format(date);
//
//                InTimeLbl.setText(currentdate);
//                try {
//                    Thread.sleep(1000);
//                } catch (InterruptedException ex) {
//
//                }
//            }
//        }).start();
    }
    
}
